"""
Django settings for instagram project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# setting 파일을 개발, 배포환경으로 구분하기 위해 수정됨, parent.parent
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 프로덕션 환경에서는 서버의 환경변수로 해당 키를 설정한 뒤 사용하는 방식으로 수정해야 할 것이다.
SECRET_KEY = '@ff4=#h7p1-a&2yeo4d)q=w26$ckz-l#+dqr2!d-s7t*q7t%3&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third Apps
    'bootstrap4',
    'debug_toolbar',
    # Local Apps
    'accounts',
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'instagram.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # template 조회에 사용되는 경로
        'DIRS': [BASE_DIR / 'instagram' / 'templates'],
        # 어플리케이션 내의 템플릿 소스 파일을 찾을지의 여부
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'instagram.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ko'    # 수정, en-us

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
# static 파일이 조회될 때 사용되는 url 경로.
STATIC_URL = '/static/'
# 기본적으로 사용되는 FileSystemFinder가 static 파일을 조회할 때 추가적으로 조회하는 경로.
STATICFILES_DIRS = [BASE_DIR / "instagram" / "static"]
# static 파일들을 collectstatic 명령으로 한 곳으로 수집할 때 수집되는 경로.
STATIC_ROOT = BASE_DIR / "static"


# media 파일을 조회하는데에 사용되는 url 경로.
MEDIA_URL = '/media/'
# 클라이언트가 업로드한 파일을 보관할 디렉토리의 절대 파일 시스템 경로
MEDIA_ROOT = BASE_DIR / "media"


# auth 앱의 기본적으로 사용되는 유저 모델을 변경하기 위한 설정
AUTH_USER_MODEL = "accounts.User"


# debug_toolbar를 활용하기 위한 설정
# https://django-debug-toolbar.readthedocs.io/en/latest/installation.html
INTERNAL_IPS = ['127.0.0.1']