# Generated by Django 3.1.2 on 2020-10-30 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='태그')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='instagram/post/%Y/%m/%d', verbose_name='사진')),
                ('caption', models.CharField(max_length=500, verbose_name='설명')),
                ('location', models.CharField(blank=True, max_length=50, verbose_name='지역')),
                ('created_at_dt', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at_dt', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag_set', models.ManyToManyField(blank=True, to='instagram.Tag')),
            ],
        ),
    ]
